# Generated by Django 4.2.11 on 2024-04-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='country_code',
            field=models.CharField(choices=[('IE', 'Ireland')], default='IE', max_length=2),
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='second_line_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
