# Generated by Django 4.2.11 on 2024-04-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_country_code_customer_mobile_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='eir_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_line_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='second_line_address',
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile_phone',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
