# Generated by Django 4.2.11 on 2024-04-06 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_customer_country_code_and_more'),
        ('kitchen', '0003_alter_order_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_first_line',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='eir_code',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.OneToOneField(default='a', on_delete=django.db.models.deletion.CASCADE, related_name='order_email', to='customer.customer', to_field='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='mobile_phone',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_mobile_phone', to='customer.customer', to_field='mobile_phone'),
            preserve_default=False,
        ),
    ]
